apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-eureka
  template:
    metadata:
      labels:
        app: microservicio-eureka
    spec:
      containers:
        - name: app
          image: microservicio-eureka:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-eureka
spec:
  selector:
    app: microservicio-eureka
  ports:
    - port: 8761
      targetPort: 8761
  type: LoadBalancer